"""empty message

Revision ID: 6bed6fe46040
Revises: 69b15b87f0dd
Create Date: 2022-01-15 14:36:05.415082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bed6fe46040'
down_revision = '69b15b87f0dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('secondname', sa.String(length=100), nullable=True))
    op.drop_column('user', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'secondname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
